spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mynet?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: liqifeng
    password: 11111111
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hiberanate:
       format_sql: true

server:
    port: 8157

